"""Helpers for tests: a fake managed environment with instant stand-in tools.

These fakes exercise the real resolver, runner, and executor code paths without
paying for genuine bioinformatics tools. Tests that use them are mocked; tests
that use the machine's installed environment are marked as real.
"""

from pathlib import Path
import os
import stat
import sys
import tempfile

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "app"))

from backend.config import BioFlowConfig, DEFAULT_ENVIRONMENT_NAMES  # noqa: E402


MICROMAMBA_SHIM = """#!/usr/bin/env bash
# Stand-in for micromamba: understands `run -r ROOT -n NAME tool args...`
set -euo pipefail
if [[ "${1:-}" != "run" ]]; then echo "unsupported: $*" >&2; exit 64; fi
shift
ROOT=""; NAME=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    -r) ROOT="$2"; shift 2 ;;
    -n) NAME="$2"; shift 2 ;;
    *) break ;;
  esac
done
exec "$ROOT/envs/$NAME/bin/$1" "${@:2}"
"""


def make_config(root: Path) -> BioFlowConfig:
    """A configuration rooted entirely inside a temporary directory."""
    return BioFlowConfig(
        data_root=root,
        database_root=root / "databases",
        environment_names=dict(DEFAULT_ENVIRONMENT_NAMES),
    )


def _write_executable(path: Path, body: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return path


def install_fake_micromamba(config: BioFlowConfig) -> Path:
    return _write_executable(config.micromamba_binary, MICROMAMBA_SHIM)


def install_fake_tool(config: BioFlowConfig, environment_key: str, tool: str, body: str) -> Path:
    """Put a stand-in executable inside a BioFlow environment prefix."""
    return _write_executable(config.environment_prefix(environment_key) / "bin" / tool, body)


def succeeding_tool(*written_files: str) -> str:
    """A tool that exits zero and creates the named files with real content."""
    lines = ["#!/usr/bin/env bash", "set -euo pipefail", 'echo "stand-in tool: $0 $*"']
    for target in written_files:
        lines.append(f'mkdir -p "$(dirname "{target}")"')
        lines.append(f'printf "%s\\n" "generated by the stand-in tool" > "{target}"')
    lines.append("exit 0")
    return "\n".join(lines) + "\n"


def failing_tool(message: str = "stand-in failure", code: int = 3) -> str:
    return (
        "#!/usr/bin/env bash\n"
        f'echo "{message}" >&2\n'
        f"exit {code}\n"
    )


def install_fake_database(config: BioFlowConfig, *parts: str, marker: str) -> Path:
    directory = config.database_directory(*parts)
    directory.mkdir(parents=True, exist_ok=True)
    target = directory / marker
    target.write_text("stand-in database marker", encoding="utf-8")
    return target


def write_fastq(
    path: Path,
    records: int = 4,
    mate: str = "",
    compress: bool | None = None,
    read_length: int = 100,
) -> Path:
    """Write a small but structurally valid FASTQ file.

    Reads default to 100 bases because real trimmers discard very short reads,
    which would make a smoke test fail for reasons unrelated to the pipeline.
    """
    import gzip
    import random

    path.parent.mkdir(parents=True, exist_ok=True)
    generator = random.Random(f"bioflow:{path.name}")
    lines = []
    for index in range(records):
        suffix = f"/{mate}" if mate else ""
        sequence = "".join(generator.choice("ACGT") for _ in range(read_length))
        lines.append(f"@read{index}{suffix}")
        lines.append(sequence)
        lines.append("+")
        lines.append("I" * read_length)
    body = "\n".join(lines) + "\n"
    use_gzip = path.name.endswith(".gz") if compress is None else compress
    if use_gzip:
        with gzip.open(path, "wt") as handle:
            handle.write(body)
    else:
        path.write_text(body, encoding="utf-8")
    return path


#: Every environment variable that can point BioFlow at real user state.
BIOFLOW_ENVIRONMENT_VARIABLES = (
    "BIOFLOW_DATA_DIR",
    "BIOFLOW_MICROMAMBA",
    "BIOFLOW_MAMBA_ROOT_PREFIX",
    "BIOFLOW_GRCH38_INDEX",
    "BIOFLOW_METAPHLAN_DB",
    "BIOFLOW_HISTORY_DB",
    "BIOFLOW_EXECUTION_BACKEND",
)


def clear_bioflow_environment() -> None:
    """Stop the developer's own BioFlow installation leaking into a test.

    Clearing alone is not isolation: with no BIOFLOW_DATA_DIR set, the
    configuration falls back to the user's real data directory. Anything that
    loads configuration must call isolate_bioflow_data_directory() as well.
    """
    for variable in BIOFLOW_ENVIRONMENT_VARIABLES:
        os.environ.pop(variable, None)


def isolate_bioflow_data_directory(test_case) -> Path:
    """Run one test against a private, empty BIOFLOW_DATA_DIR.

    Returns the temporary directory. Cleanup is registered on the test case, so
    the previous environment and the cached configuration are restored even if
    the test fails part-way through.

    The configuration is cached process-wide, so the cache is reset both after
    pointing at the temporary directory and after restoring the environment;
    otherwise a stale object would outlive the directory it describes.
    """
    from backend.config import reload_config

    previous = {name: os.environ.get(name) for name in BIOFLOW_ENVIRONMENT_VARIABLES}
    temporary = tempfile.TemporaryDirectory(prefix="bioflow-isolated-")

    def restore() -> None:
        for name, value in previous.items():
            if value is None:
                os.environ.pop(name, None)
            else:
                os.environ[name] = value
        reload_config()

    # Cleanups run last-registered-first: restore the environment and reset the
    # cached configuration before the directory it points at is removed.
    test_case.addCleanup(temporary.cleanup)
    test_case.addCleanup(restore)

    clear_bioflow_environment()
    os.environ["BIOFLOW_DATA_DIR"] = temporary.name
    reload_config()
    return Path(temporary.name)


def install_fake_environment(config, key: str) -> None:
    """Create an environment prefix that looks genuinely complete.

    BioFlow treats an environment as installed only when the tools it declares
    are actually present, so a test that only makes `bin` is describing a
    failed installation rather than a successful one.
    """
    from backend.setup.registry import environment_specs

    binaries = config.environment_prefix(key) / "bin"
    binaries.mkdir(parents=True, exist_ok=True)
    spec = environment_specs().get(key)
    for command in spec.verify_commands if spec else ():
        (binaries / command[0]).write_bytes(b"")


def enable_functional_profiling(test_case) -> None:
    """Turn on the components this release withholds, for the duration of a test.

    Functional profiling is gated out of the release but still fully present in
    the codebase, so the tests that cover it enable it explicitly rather than
    being deleted alongside the feature.
    """
    import os

    previous = os.environ.get("BIOFLOW_ENABLE_FUNCTIONAL")

    def restore():
        if previous is None:
            os.environ.pop("BIOFLOW_ENABLE_FUNCTIONAL", None)
        else:
            os.environ["BIOFLOW_ENABLE_FUNCTIONAL"] = previous

    test_case.addCleanup(restore)
    os.environ["BIOFLOW_ENABLE_FUNCTIONAL"] = "1"
